# Generated by Django 4.1 on 2022-12-14 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=199, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Thiruvanathapuram', 'tvm'), ('Ernakulam', 'ekm'), ('Calicut', 'clt'), ('Thrissur', 'thr'), ('Kottayam', 'ktym')], max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=100)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.BooleanField()),
                ('phonenumber', models.IntegerField(blank=True)),
                ('mailid', models.EmailField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('account', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=200)),
                ('material', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Pass Book', 'Pass Book')], max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.districts')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.districts'),
        ),
    ]
