# Generated by Django 4.1 on 2022-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=models.CharField(choices=[('Thiruvanathapuram', 'tvm'), ('Ernakulam', 'ekm'), ('Calicut', 'clt'), ('wayanad', 'wyd'), ('kannur', 'knr')], max_length=100, unique=True),
        ),
    ]
